/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package usuarios.vistas;

import interfaces.IControladorAMUsuario;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import usuarios.controladores.ControladorAMUsuario;
import usuarios.modelos.ModeloComboPerfil;

/**
 *
 * @author tomascabrerabellomo
 */
public class VentanaCrearYModificarUsuario extends javax.swing.JDialog {

    // controlador
    private IControladorAMUsuario controlador;

    /**
     * Creates new form Ventanacrear_modificarusuario
     */
    public VentanaCrearYModificarUsuario(java.awt.Frame parent, boolean modal, IControladorAMUsuario controlador) {
        super(parent, modal);
        this.controlador = controlador;
        this.configurarperfil();
        initComponents();
    }

    private void configurarperfil() {
        ModeloComboPerfil modelo = new ModeloComboPerfil();
        this.ComboPerfil.setModel(modelo);
    }

    public JComboBox<String> obtenerComboPerfil() {
        return ComboPerfil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correo = new javax.swing.JLabel();
        botoncancelar = new javax.swing.JButton();
        botonguardar = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        clave = new javax.swing.JLabel();
        claveduplicada = new javax.swing.JLabel();
        textocorreo = new javax.swing.JTextField();
        textoapellido = new javax.swing.JTextField();
        textonombre = new javax.swing.JTextField();
        contraseñatexto = new javax.swing.JPasswordField();
        contraseñareptexto = new javax.swing.JPasswordField();
        ComboPerfil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        correo.setText("Correo:");

        botoncancelar.setText("Cancelar");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });

        botonguardar.setText("Guardar");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });

        nombre.setText("Nombre:");

        apellido.setText("Apellido:");

        perfil.setText("Perfil:");

        clave.setText("Clave:");

        claveduplicada.setText("Repetir clave:");

        textocorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textocorreoActionPerformed(evt);
            }
        });
        textocorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textocorreoKeyTyped(evt);
            }
        });

        textoapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoapellidoActionPerformed(evt);
            }
        });
        textoapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoapellidoKeyTyped(evt);
            }
        });

        textonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textonombreActionPerformed(evt);
            }
        });
        textonombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textonombreKeyTyped(evt);
            }
        });

        contraseñatexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñatextoActionPerformed(evt);
            }
        });
        contraseñatexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseñatextoKeyTyped(evt);
            }
        });

        contraseñareptexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñareptextoActionPerformed(evt);
            }
        });
        contraseñareptexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseñareptextoKeyTyped(evt);
            }
        });

        ComboPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonguardar)
                .addGap(18, 18, 18)
                .addComponent(botoncancelar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correo)
                    .addComponent(apellido)
                    .addComponent(nombre)
                    .addComponent(perfil)
                    .addComponent(clave)
                    .addComponent(claveduplicada))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textocorreo)
                    .addComponent(textoapellido)
                    .addComponent(textonombre)
                    .addComponent(ComboPerfil, 0, 200, Short.MAX_VALUE)
                    .addComponent(contraseñatexto)
                    .addComponent(contraseñareptexto))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo)
                    .addComponent(textocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido)
                    .addComponent(textoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(textonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfil)
                    .addComponent(ComboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave)
                    .addComponent(contraseñatexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveduplicada)
                    .addComponent(contraseñareptexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoncancelar)
                    .addComponent(botonguardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // getter para el comboPerfil
//    public JComboBox verCategoria() {
//        return this.comboCategoria;
//    }

    private void contraseñatextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñatextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñatextoActionPerformed

    private void contraseñareptextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñareptextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñareptextoActionPerformed

    private void textocorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textocorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textocorreoActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
        this.controlador.btnGuardarClic(evt);
    }//GEN-LAST:event_botonguardarActionPerformed

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.controlador.btnCancelarClic(evt);
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void textocorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textocorreoKeyTyped
        this.controlador.txtCorreoPresionarTecla(evt);
    }//GEN-LAST:event_textocorreoKeyTyped

    private void textoapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoapellidoKeyTyped
        this.controlador.txtApellidoPresionarTecla(evt);
    }//GEN-LAST:event_textoapellidoKeyTyped

    private void textonombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textonombreKeyTyped
        this.controlador.txtNombrePresionarTecla(evt);
    }//GEN-LAST:event_textonombreKeyTyped

    private void contraseñatextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñatextoKeyTyped
        this.controlador.passClavePresionarTecla(evt);
    }//GEN-LAST:event_contraseñatextoKeyTyped

    private void contraseñareptextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñareptextoKeyTyped
        this.controlador.passClaveRepetidaPresionarTecla(evt);
    }//GEN-LAST:event_contraseñareptextoKeyTyped

    private void textoapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoapellidoActionPerformed

    private void textonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textonombreActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaCrearYModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaCrearYModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaCrearYModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaCrearYModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                VentanaCrearYModificarUsuario dialog = new VentanaCrearYModificarUsuario(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    public JButton verbotonguardar() {
        return botonguardar;
    }
     public JButton verbotoncancelar() {
        return botoncancelar;
    }
     public void asignarbotonCancelar(JButton botoncancelar) {
        this.botoncancelar = botoncancelar;
    }
     public void asignarbotonguardar(JButton botonguardar) {
        this.botonguardar = botonguardar;
    }
    public JComboBox<String> verComboPerfiles() {
        return ComboPerfil;
    }
    public void asignarComboPerfil(JComboBox<String> ComboPerfil) {
        this.ComboPerfil = ComboPerfil;
    }
    public IControladorAMUsuario getControlador() {
        return controlador;
    }

    public void asignarControlador(IControladorAMUsuario controlador) {
        this.controlador = controlador;
    }

    public JLabel verApellido() {
        return apellido;
    }

    public void asignarApellido(JLabel apellido) {
        this.apellido = apellido;
    }

    public JLabel verClave() {
        return clave;
    }

    public void asignarClave(JLabel clave) {
        this.clave = clave;
    }

    public JLabel verClaveduplicada() {
        return claveduplicada;
    }

    public void asignarClaveduplicada(JLabel claveduplicada) {
        this.claveduplicada = claveduplicada;
    }

    public JPasswordField verContraseñareptexto() {
        return contraseñareptexto;
    }

    public void asignarContraseñareptexto(JPasswordField contraseñareptexto) {
        this.contraseñareptexto = contraseñareptexto;
    }

    public JPasswordField verContraseñatexto() {
        return contraseñatexto;
    }

    public void asignarContraseñatexto(JPasswordField contraseñatexto) {
        this.contraseñatexto = contraseñatexto;
    }

    public JLabel verCorreo() {
        return correo;
    }

    public void asignarCorreo(JLabel correo) {
        this.correo = correo;
    }

    public JLabel verNombre() {
        return nombre;
    }

    public void asignarNombre(JLabel nombre) {
        this.nombre = nombre;
    }

    public JLabel verPerfil() {
        return perfil;
    }

    public void asignarPerfil(JLabel perfil) {
        this.perfil = perfil;
    }

    public JTextField verTextoapellido() {
        return textoapellido;
    }

    public void asignarTextoapellido(JTextField textoapellido) {
        this.textoapellido = textoapellido;
    }

    public JTextField verTextocorreo() {
        return textocorreo;
    }

    public void asignarTextocorreo(JTextField textocorreo) {
        this.textocorreo = textocorreo;
    }

    public JTextField verTextonombre() {
        return textonombre;
    }

    public void asignarTextonombre(JTextField textonombre) {
        this.textonombre = textonombre;
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboPerfil;
    private javax.swing.JLabel apellido;
    private javax.swing.JButton botoncancelar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JLabel clave;
    private javax.swing.JLabel claveduplicada;
    private javax.swing.JPasswordField contraseñareptexto;
    private javax.swing.JPasswordField contraseñatexto;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel perfil;
    private javax.swing.JTextField textoapellido;
    private javax.swing.JTextField textocorreo;
    private javax.swing.JTextField textonombre;
    // End of variables declaration//GEN-END:variables
}
