/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package usuarios.vistas;

import interfaces.IControladorAMUsuario;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author tomascabrerabellomo
 */
public class VentanaCrearYModificarUsuario extends javax.swing.JDialog {

    // controlador
    private IControladorAMUsuario controlador;

    /**
     * Creates new form Ventanacrear_modificarusuario
     */
    public VentanaCrearYModificarUsuario(java.awt.Dialog parent, boolean modal, IControladorAMUsuario controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
    }

    public JComboBox<String> obtenerComboPerfil() {
        return comboPerfil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correo = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        clave = new javax.swing.JLabel();
        claveDuplicada = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JTextField();
        textoApellido = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        textoContrasenia = new javax.swing.JPasswordField();
        textoContraseniaRep = new javax.swing.JPasswordField();
        comboPerfil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        correo.setText("Correo:");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        nombre.setText("Nombre:");

        apellido.setText("Apellido:");

        perfil.setText("Perfil:");

        clave.setText("Clave:");

        claveDuplicada.setText("Repetir clave:");

        textoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCorreoActionPerformed(evt);
            }
        });
        textoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoCorreoKeyTyped(evt);
            }
        });

        textoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidoActionPerformed(evt);
            }
        });
        textoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoApellidoKeyTyped(evt);
            }
        });

        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });

        textoContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseniaActionPerformed(evt);
            }
        });
        textoContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoContraseniaKeyTyped(evt);
            }
        });

        textoContraseniaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseniaRepActionPerformed(evt);
            }
        });
        textoContraseniaRep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoContraseniaRepKeyTyped(evt);
            }
        });

        comboPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(18, 18, 18)
                .addComponent(botonCancelar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correo)
                    .addComponent(apellido)
                    .addComponent(nombre)
                    .addComponent(perfil)
                    .addComponent(clave)
                    .addComponent(claveDuplicada))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoCorreo)
                    .addComponent(textoApellido)
                    .addComponent(textoNombre)
                    .addComponent(comboPerfil, 0, 200, Short.MAX_VALUE)
                    .addComponent(textoContrasenia)
                    .addComponent(textoContraseniaRep))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo)
                    .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido)
                    .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfil)
                    .addComponent(comboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave)
                    .addComponent(textoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveDuplicada)
                    .addComponent(textoContraseniaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseniaActionPerformed

    private void textoContraseniaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseniaRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseniaRepActionPerformed

    private void textoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCorreoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        this.controlador.btnGuardarClic(evt);
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.controlador.btnCancelarClic(evt);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoCorreoKeyTyped
        this.controlador.txtCorreoPresionarTecla(evt);
    }//GEN-LAST:event_textoCorreoKeyTyped

    private void textoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoApellidoKeyTyped
        this.controlador.txtApellidoPresionarTecla(evt);
    }//GEN-LAST:event_textoApellidoKeyTyped

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
        this.controlador.txtNombrePresionarTecla(evt);
    }//GEN-LAST:event_textoNombreKeyTyped

    private void textoContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoContraseniaKeyTyped
        this.controlador.passClavePresionarTecla(evt);
    }//GEN-LAST:event_textoContraseniaKeyTyped

    private void textoContraseniaRepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoContraseniaRepKeyTyped
        this.controlador.passClaveRepetidaPresionarTecla(evt);
    }//GEN-LAST:event_textoContraseniaRepKeyTyped

    private void textoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApellidoActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    // getters y setters
    public JButton verBotonGuardar() {
        return botonGuardar;
    }
     public JButton verBotonCancelar() {
        return botonCancelar;
    }
     public void asignarBotonCancelar(JButton botoncancelar) {
        this.botonCancelar = botoncancelar;
    }
     public void asignarBotonGuardar(JButton botonguardar) {
        this.botonGuardar = botonguardar;
    }
    public JComboBox<String> verComboPerfiles() {
        return comboPerfil;
    }
    public void asignarComboPerfil(JComboBox<String> ComboPerfil) {
        this.comboPerfil = ComboPerfil;
    }
    public IControladorAMUsuario verControlador() {
        return controlador;
    }

    public void asignarControlador(IControladorAMUsuario controlador) {
        this.controlador = controlador;
    }

    public JLabel verApellido() {
        return apellido;
    }

    public void asignarApellido(JLabel apellido) {
        this.apellido = apellido;
    }

    public JLabel verClave() {
        return clave;
    }

    public void asignarClave(JLabel clave) {
        this.clave = clave;
    }

    public JLabel verClaveDuplicada() {
        return claveDuplicada;
    }

    public void asignarClaveDuplicada(JLabel claveduplicada) {
        this.claveDuplicada = claveduplicada;
    }

    public JPasswordField verTextoContraseniaRep() {
        return textoContraseniaRep;
    }

    public void asignarTextoContraseniaRep(JPasswordField contraseñareptexto) {
        this.textoContraseniaRep = contraseñareptexto;
    }

    public JPasswordField verTextoContrasenia() {
        return textoContrasenia;
    }

    public void asignarTextoContrasenia(JPasswordField contraseñatexto) {
        this.textoContrasenia = contraseñatexto;
    }

    public JLabel verCorreo() {
        return correo;
    }

    public void asignarCorreo(JLabel correo) {
        this.correo = correo;
    }

    public JLabel verNombre() {
        return nombre;
    }

    public void asignarNombre(JLabel nombre) {
        this.nombre = nombre;
    }

    public JLabel verPerfil() {
        return perfil;
    }

    public void asignarPerfil(JLabel perfil) {
        this.perfil = perfil;
    }

    public JTextField verTextoApellido() {
        return textoApellido;
    }

    public void asignarTextoApellido(JTextField textoapellido) {
        this.textoApellido = textoapellido;
    }

    public JTextField verTextoCorreo() {
        return textoCorreo;
    }

    public void asignarTextoCorreo(JTextField textocorreo) {
        this.textoCorreo = textocorreo;
    }

    public JTextField verTextoNombre() {
        return textoNombre;
    }

    public void asignarTextoNombre(JTextField textonombre) {
        this.textoNombre = textonombre;
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel clave;
    private javax.swing.JLabel claveDuplicada;
    private javax.swing.JComboBox<String> comboPerfil;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel perfil;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JPasswordField textoContrasenia;
    private javax.swing.JPasswordField textoContraseniaRep;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
